apiVersion: v1
data:
  vault-agent-config.hcl: |
    # Comment this out if running as sidecar instead of initContainer
    # exit_after_auth = true

    pid_file = "/home/vault/pidfile"

    auto_auth {
        method "kubernetes" {
            mount_path = "auth/kubernetes"
            config = {
                role = "example"
            }
        }

        sink "file" {
            config = {
                path = "/home/vault/.vault-token"
            }
        }
    }

    template {
    destination = "/etc/secrets/index.html"
    contents = <<EOT
    <html>
    <body>
    <p>Some secrets:</p>
    {{- with secret "secret/data/myapp/config" }}
    <ul>
    <li><pre>username: {{ .Data.data.username }}</pre></li>
    <li><pre>password: {{ .Data.data.password }}</pre></li>
    <li><pre>keytab: {{ .Data.data.keytab }}</pre></li>
    </ul>
    {{ end }}

    {{ with secret "intca/issue/example" "common_name=client-4.clients.alice.com" }}
    <ul>
    <li><pre>clientCrt: {{ .Data.certificate }}</pre></li>
    <li><pre>clientKey: {{ .Data.private_key }}</pre></li>
    <li><pre>CA chain: {{ .Data.ca_chain }}</pre></li>
    </ul>
    {{ end }}

    {{ with secret "database/creds/fruit-catalog-role" }}
    <ul>
    <li><pre>Mongo username: {{ .Data.username }}</pre></li>
    <li><pre>Mongo password: {{ .Data.password }}</pre></li>
    </ul>
    {{ end }}
    </body>
    </html>
    EOT
    }

    template {
    contents = <<EOH
    {{- with secret "secret/data/myapp/config" }}
    {{- base64Decode .Data.data.keytab -}}
    {{ end }}
    EOH
    destination = "/etc/secrets/kafka.keytab"
    }


    template {
    contents = <<EOH
    {{- $hostname := env "HOSTNAME" -}}
    {{- $hostip := env "HOSTIP" -}}
    {{- $alt_arg := printf "alt_names=%s,%s.%s" $hostname $hostname "development.svc.cluster.local" -}}
    {{- $ip_arg := printf "ip_sans=127.0.0.1,%s" $hostip -}}
    {{ with secret "intca/issue/example" "common_name=client-4.clients.alice.com" "ttl=24h" $alt_arg $ip_arg }}
    {{- .Data.certificate -}}
    {{ end }}
    EOH
    destination = "/etc/secrets/client-4.pem"
    }

    template {
    contents = <<EOH
    {{- $hostname := env "HOSTNAME" -}}
    {{- $hostip := env "HOSTIP" -}}
    {{- $alt_arg := printf "alt_names=%s,%s.%s" $hostname $hostname "development.svc.cluster.local" -}}
    {{- $ip_arg := printf "ip_sans=127.0.0.1,%s" $hostip -}}
    {{ with secret "intca/issue/example" "common_name=client-4.clients.alice.com" "ttl=24h" $alt_arg $ip_arg }}
    {{- .Data.private_key -}}
    {{ end }}
    EOH
    destination = "/etc/secrets/private_key.key"
    }

    template {
    contents = <<EOH
    {{ with secret "intca/issue/example" "common_name=client-4.clients.alice.com" "ttl=24h" }}
    {{- .Data.issuing_ca -}}
    {{ end }}
    EOH
    destination = "/etc/secrets/intca.pem"
    }

    template {
    contents = <<EOH
    {{ with secret "intca/issue/example" "common_name=client-4.clients.alice.com" "ttl=24h" }}
    {{ range $idx, $cert := .Data.ca_chain }}{{ $cert }}
    {{ end }}
    {{ end }}
    EOH
    destination = "/etc/secrets/ca_chain.pem"
    }

kind: ConfigMap
metadata:
  name: example-vault-agent-config
  namespace: development
