apiVersion: v1
kind: Pod
metadata:
  name: vault-agent-example
  namespace: development
spec:
  serviceAccountName: vault

  volumes:
  - configMap:
      items:
      - key: vault-agent-config.hcl
        path: vault-agent-config.hcl
      name: example-vault-agent-config
    name: config
  - name: vault-token
    emptyDir:
      medium: Memory
  - emptyDir:
      medium: Memory
    name: shared-data

  initContainers:
  - args:
    - agent
    - -config=/etc/vault/vault-agent-config.hcl
    - -log-level=debug
    - -exit-after-auth
    env:
    - name: SKIP_SETCAP
      value: 'true'      
    - name: VAULT_ADDR
      value: http://vault:8200
    - name: HOSTIP
      valueFrom:
       fieldRef:
        fieldPath: status.podIP
    image: vault
    name: vault-agent-init
    volumeMounts:
    - mountPath: /etc/vault
      name: config
    - mountPath: /etc/secrets
      name: shared-data
    - mountPath: /home/vault
      name: vault-token
  containers:
  - image: vault
    name: vault-agent
    volumeMounts:
    - mountPath: /etc/vault
      name: config
    - mountPath: /etc/secrets
      name: shared-data
    - mountPath: /home/vault
      name: vault-token
    args:
    - agent
    - -config=/etc/vault/vault-agent-config.hcl
    - -log-level=debug
    env:
    - name: SKIP_SETCAP
      value: 'true'
    - name: VAULT_ADDR
      value: http://vault:8200
    - name: HOSTIP
      valueFrom:
       fieldRef:
        fieldPath: status.podIP
    lifecycle:
      preStop:
        exec:
          command:
          - /bin/sh
          - -c
            - sleep 5 && kill -SIGTERM $(pidof vault)
  - image: nginx
    name: nginx-container
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: shared-data
