apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: vault-issuer-istio
  namespace: istio-system
spec:
  vault:
    path: intca/sign/example
    server: http://vault.development.svc.cluster.local:8200
    auth:
      kubernetes:
        role: example
        mountPath: /v1/auth/kubernetes
        secretRef:
          name: istio-ingressgateway-service-account-token-2zlrm
          key: token
