apiVersion: v1
data:
  default.conf: |
     server {
      listen       443 ssl;
      server_name  localhost;

      ssl_certificate /etc/nginx/conf.d/certs/server.crt;
      ssl_certificate_key /etc/nginx/conf.d/certs/server.key;

      ssl_client_certificate /etc/nginx/conf.d/certs/ca.crt;
      ssl_verify_depth 3;
      ssl_verify_client on;

      location / {
          if ($ssl_client_s_dn != "CN=client-1.clients.alice.com") {
              return 403 '{"code":"403", "message": "Request Failed : $ssl_client_s_dn"}';
          }
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        #  return 200 '{"code":"200", "message": "Request successful : $ssl_client_s_dn"}';
        }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
        }
      }

kind: ConfigMap
metadata:
  name: nginx
  namespace: development
